// import aida from '../assets/templateIcon/aida.png';
// import pas from '../assets/templateIcon/pas.png';
// import contentImprover from '../assets/templateIcon/contentImprover.png';
// import photoCaption from '../assets/templateIcon/photoCaption.png';
// import emailSubjectLines from '../assets/templateIcon/emailSubjectLines.png';
// import star from '../assets/star.png';

// export const approveTemplateList = [
//   {
//     id: 'aida',
//     isVisible: true,
//     description: 'Use the oldest marketing framework in the world. Attention, Interest, Desire, Action.',
//     categories: 'framework',
//     fields: [
//       {
//         type: 'input',
//         toolTipText: null,
//         placeholder: '',
//         characterLimit: 80,
//         optional: true,
//         subtitle: null,
//         key: 'i1',
//         name: 'Company/Product name',
//       },
//       {
//         subtitle: null,
//         optional: false,
//         placeholder: '',
//         key: 'i2',
//         characterLimit: 300,
//         name: 'Product Description',
//         type: 'textarea',
//         toolTipText: null,
//       },
//       {
//         subtitle: null,
//         optional: true,
//         placeholder: '',
//         key: 'tone',
//         characterLimit: 80,
//         name: 'Tone',
//         type: 'input',
//         toolTipText: null,
//       },
//     ],
//     title: 'AIDA Framework',
//     image: aida,
//   },
//   {
//     id: 'pas',
//     isVisible: true,
//     description: 'Problem-Agitate-Solution. A valuable framework for creating new marketing copy ideas.',
//     categories: 'framework',
//     fields: [
//       {
//         type: 'input',
//         toolTipText: null,
//         placeholder: '',
//         characterLimit: 80,
//         optional: true,
//         subtitle: null,
//         key: 'i1',
//         name: 'Company/Product name',
//       },
//       {
//         subtitle: null,
//         optional: false,
//         placeholder: '',
//         key: 'i2',
//         characterLimit: 300,
//         name: 'Product Description',
//         type: 'textarea',
//         toolTipText: null,
//       },
//       {
//         subtitle: null,
//         optional: true,
//         placeholder: '',
//         key: 'tone',
//         characterLimit: 80,
//         name: 'Tone',
//         type: 'input',
//         toolTipText: null,
//       },
//     ],
//     title: 'PAS Framework',
//     image: pas,
//   },
//   {
//     id: 'contentImprover',
//     isVisible: true,
//     description: 'Take a piece of content and rewrite it to make it more interesting, creative, and engaging.',
//     fields: [
//       {
//         subtitle: null,
//         optional: false,
//         placeholder: '',
//         key: 'i1',
//         characterLimit: 300,
//         name: 'Content',
//         type: 'textarea',
//         toolTipText: null,
//       },
//       {
//         subtitle: null,
//         optional: true,
//         placeholder: '',
//         key: 'tone',
//         characterLimit: 80,
//         name: 'Tone',
//         type: 'input',
//         toolTipText: null,
//       },
//     ],
//     title: 'Content Improver',
//     image: contentImprover,
//     star: star,
//     categories: 'social',
//   },
//   {
//     id: 'photoPostCaption',
//     isVisible: true,
//     categories: 'social',
//     description: 'Write catchy captions for your Instagram posts',
//     fields: [
//       {
//         subtitle: null,
//         optional: false,
//         placeholder: '',
//         key: 'i1',
//         characterLimit: 80,
//         name: 'What is your post about?',
//         type: 'input',
//         toolTipText: null,
//       },
//       {
//         subtitle: null,
//         optional: true,
//         placeholder: '',
//         key: 'tone',
//         characterLimit: 80,
//         name: 'Tone',
//         type: 'input',
//         toolTipText: null,
//       },
//     ],
//     title: 'Photo Post Captions',
//     image: photoCaption,
//   },
//   {
//     id: 'photoPostCaptionShort',
//     isVisible: true,
//     categories: 'social',
//     description: 'Write catchy captions for your Instagram posts',
//     fields: [
//       {
//         subtitle: null,
//         optional: false,
//         placeholder: '',
//         key: 'i1',
//         characterLimit: 80,
//         name: 'What is your post about?',
//         type: 'input',
//         toolTipText: null,
//       },
//       {
//         subtitle: null,
//         optional: true,
//         placeholder: '',
//         key: 'tone',
//         characterLimit: 80,
//         name: 'Tone',
//         type: 'input',
//         toolTipText: null,
//       },
//     ],
//     title: 'Photo Post Caption(Short)',
//     image: photoCaption,
//   },
//   {
//     id: 'emailSubjectLines',
//     isVisible: true,
//     description: 'Write compelling email subject lines that get readers to open.',
//     categories: 'email',
//     fields: [
//       {
//         type: 'input',
//         toolTipText: null,
//         placeholder: '',
//         characterLimit: 80,
//         optional: true,
//         subtitle: null,
//         key: 'i1',
//         name: 'Company/Product name',
//       },
//       {
//         subtitle: null,
//         optional: false,
//         placeholder: '',
//         key: 'i2',
//         characterLimit: 300,
//         name: 'What is your email about?',
//         type: 'textarea',
//         toolTipText: null,
//       },
//       {
//         subtitle: null,
//         optional: true,
//         placeholder: '',
//         key: 'tone',
//         characterLimit: 80,
//         name: 'Tone',
//         type: 'input',
//         toolTipText: null,
//       },
//     ],
//     title: 'Email Subject Lines',
//     image: emailSubjectLines,
//   },
// ];
