/* eslint-disable @next/next/inline-script-id */
/* eslint-disable @next/next/no-script-component-in-head */
import { useEffect } from 'react';
import { Button } from 'antd';
import Head from 'next/head';
import Script from 'next/script';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useDispatch, useSelector } from 'react-redux';
import { Helmet } from 'react-helmet';
import { firebaseAuth } from '../firebase';
import { useAuthState } from 'react-firebase-hooks/auth';
import { invitemode, inviteteamMember, resetPasswordCode } from '../features/auth/authSlice';

export default function Home() {
  const [user] = useAuthState(firebaseAuth);
  const router = useRouter();
  const dispatch = useDispatch();
  useEffect(() => {
    const queryParam = new URLSearchParams(window.location.search);
    const actionCode = queryParam.get('oobCode');
    const mode = queryParam.get('mode');
    if (user) {
      router.push('./dashboard');
    } else {
      if (mode === 'resetPassword') {
        dispatch(resetPasswordCode(actionCode));
        router.push('./reset-password');
      } else if (mode === 'signIn') {
        router.push('./invite');
        dispatch(inviteteamMember(window.location.href));
        dispatch(invitemode(mode));
      } else if (mode === null) {
        router.push('./login');
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user]);

  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
